### ISSUE TITLE
Rebase crashes if it encounters a merge conflict

### ISSUE THREAD

**Issue by taneliang** [taneliang/stack-attack#65]
If a rebase causes a merge conflict, Stack Attack crashes with a cryptic error message

Example repro:

Crash when rebase `b86cede` is rebased onto `fc5d26c`:

![image](https://user-images.githubusercontent.com/12784593/90363421-4cb68380-e095-11ea-8301-d6187876381f.png)

Stack Attack crash:

![image](https://user-images.githubusercontent.com/12784593/90363377-35779600-e095-11ea-8890-8a4d3f5d142c.png)

What git shows when I try to do a similar rebase manually:

![image](https://user-images.githubusercontent.com/12784593/90364670-0b26d800-e097-11ea-8f22-73800311a104.png)

## Acceptance Criteria

- [ ] Error thrown should be nicer
- [ ] Recover from the crash (Stack Attack is currently unresponsive after the crash)

**Comment by saphal1998** [comment]
Any ideas on how to make this operation atomic? I think that's the way to actually solve this issue.

Temporary solution (imo) - If there's a merge conflict in the stack, we can throw an error, but we should also inform the user to rebase from the conflict commit to avoid unnecessary commits.

**Comment by taneliang** [comment]
> Any ideas on how to make this operation atomic? I think that's the way to actually solve this issue.

Hmm, I think this will only improve our handling of these conflicts. Ideally we'll want to pause the rebasing, allow the user to resolve the conflict outside, then allow them to continue. Of course, is most likely going to be too complicated for the MVP 😆 

> Temporary solution (imo) - If there's a merge conflict in the stack, we can throw an error, but we should also inform the user to rebase from the conflict commit to avoid unnecessary commits.

Yep. I think the frontend needs to catch the thrown error and present it to the user (the "Recover from crash" part) in the acceptance criteria. This error message can contain instructions (i.e. Git CLI commands) to help them manually cherry pick the problematic commit before continuing the rebase with Stack Attack. I'm thinking something like this:

```
Stack Attack has rebased commits up till `e5ab634`, but encountered a conflict when rebasing commit `b86cede`. Please run the following commands to resolve it:

git checkout stack-attack/rebase-target  # A branch pointing to the last commit that was successfully cherry picked
git cherry-pick b86cede
# Resolve conflicts
git branch -f branch1 branch2  # Move the branches from the original commit (I'm not actually sure if git branch -f does what we want; gotta confirm. May also need to ensure that moved branches still track their remote branches)
sttack rebase d8aa808 stack-attack/rebase-target  # Stretch goal: continuation command. Rebase the next commit after `b86cede` (i.e. the imaginary d8aa808) onto the rebase target branch. Obviously if we want to do this, rebaseCommits needs to accept branches 😆
```

**Comment by taneliang** [comment]
@saphal1998 here's a repro: https://github.com/24r/stack-attack-issue-65-repro

Rebase commit 3 on 1 and it should crash
